# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='documents')),
                ('imagem2', models.FileField(upload_to='documents')),
            ],
        ),
    ]
