# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpproxy', '0002_auto_20160121_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestparameter',
            name='type',
            field=models.CharField(choices=[('G', 'GET'), ('P', 'POST')], default='G', max_length=1),
        ),
    ]
