# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Somar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('valor1', models.IntegerField()),
                ('valor2', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
