# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0002_somar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somar',
            name='valor1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='somar',
            name='valor2',
            field=models.IntegerField(default=0),
        ),
    ]
