# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0004_somar_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somar',
            name='test',
            field=models.CharField(default='friendly', max_length=100),
        ),
    ]
