# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0005_auto_20170828_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='somar',
            name='test',
        ),
    ]
