# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisador', '0006_remove_somar_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Somar',
        ),
        migrations.AddField(
            model_name='audio',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imagem',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='outros',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='texto',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
