# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_somarapi_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='somarapi',
            name='slug',
        ),
    ]
